apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - image-egress-proxy.yaml
  - redis.yaml
  - backend.yaml
  - web.yaml

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf
