services:
  app-postgres:
    image: postgres:18-alpine
    container_name: litomi-app-postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: app_db
    ports:
      - '5434:5432'
    volumes:
      - app-db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d app_db']
      interval: 5s
      timeout: 5s
      retries: 5

  catalog-postgres:
    image: postgres:18-alpine
    container_name: litomi-catalog-postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: catalog_db
    ports:
      - '5435:5432'
    volumes:
      - catalog-db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d catalog_db']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data

  srh:
    image: hiett/serverless-redis-http:latest
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: local_dev_token
      SRH_CONNECTION_STRING: 'redis://redis:6379'
    depends_on:
      - redis

volumes:
  app-db-data:
  catalog-db-data:
  redis-data:
