apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-mtls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: tempo-mtls
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: ca.crt
      remoteRef:
        key: tracing/tempo-mtls
        property: ca_crt
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: tempo.crt
      remoteRef:
        key: tracing/tempo-mtls
        property: tempo_crt
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: tempo.key
      remoteRef:
        key: tracing/tempo-mtls
        property: tempo_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: collector.crt
      remoteRef:
        key: tracing/tempo-mtls
        property: collector_crt
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: collector.key
      remoteRef:
        key: tracing/tempo-mtls
        property: collector_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
