import ms from 'ms'

export const POINT_CONSTANTS = {
  AD_CLICK_REWARD: 10,
  LIBRARY_EXPANSION_PRICE: 200,
  LIBRARY_EXPANSION_AMOUNT: 1,
  LIBRARY_MAX_EXPANSION: 30,
  HISTORY_EXPANSION_PRICE: 300,
  HISTORY_EXPANSION_AMOUNT: 100,
  HISTORY_MAX_EXPANSION: 5000,
  BOOKMARK_EXPANSION_SMALL_PRICE: 200,
  BOOKMARK_EXPANSION_SMALL_AMOUNT: 100,
  BOOKMARK_EXPANSION_LARGE_PRICE: 800,
  BOOKMARK_EXPANSION_LARGE_AMOUNT: 500,
  BOOKMARK_MAX_EXPANSION: 5000,
  BADGE_PRICE: 500,
  THEME_PRICE: 300,
  AD_SLOT_COOLDOWN_MS: ms('1 minute'),
  DAILY_EARN_LIMIT_COUNT: 10,
  TOKEN_EXPIRY_MS: ms('10 minutes'),
} as const

export const TRANSACTION_TYPE = {
  AD_CLICK: 1,
  SHOP_PURCHASE: 2,
} as const

export const EXPANSION_TYPE = {
  LIBRARY: 1,
  READING_HISTORY: 2,
  BOOKMARK: 3,
} as const

export const ITEM_TYPE = {
  BADGE: 1,
  THEME: 2,
} as const
