import { RatingSort } from '@/backend/api/v1/library/enum'
import { PostFilter } from '@/backend/api/v1/post/constant'

export const QueryKeys = {
  me: ['me'],
  bookmarks: ['me', 'bookmarks'],
  infiniteBookmarks: ['me', 'bookmarks', 'infinite'],
  infiniteReadingHistory: ['me', 'readingHistory', 'infinite'],
  infiniteRatings: (sort: RatingSort) => ['me', 'ratings', 'infinite', sort],
  censorship: ['me', 'censorships'],
  infiniteCensorships: ['me', 'censorships', 'infinite'],
  passkeys: ['me', 'passkeys'],
  notification: ['me', 'notifications'],
  notificationUnreadCount: ['me', 'notifications', 'unread-count'],
  notifications: (searchParams: URLSearchParams) => ['me', 'notifications', Object.fromEntries(searchParams)],
  libraries: ['me', 'libraries'],
  infiniteLibraryListBase: ['library', 'list', 'infinite'],
  infiniteLibraryMangasBase: ['library', 'manga', 'infinite'],
  infiniteLibraryList: (userId: number | null) => [...QueryKeys.infiniteLibraryListBase, userId ?? 'guest'],
  infiniteLibraryMangas: (userId: number | null) => [...QueryKeys.infiniteLibraryMangasBase, userId ?? 'guest'],
  librarySummary: (userId: number | null) => ['library', 'summary', userId ?? 'guest'],
  libraryMeta: (libraryId: number, userId: number | null) => ['library', 'meta', libraryId, userId ?? 'guest'],
  libraryItems: (libraryId: number) => ['me', 'library', libraryId],
  userRating: (mangaId: number) => ['me', 'rating', mangaId],
  readingHistory: (mangaId: number) => ['me', 'readingHistory', mangaId],
  points: ['me', 'points'],
  pointsExpansion: ['me', 'points', 'expansion'],
  pointsTurnstile: ['me', 'points', 'turnstile'],
  pointsTransactions: ['me', 'points', 'transactions'],
  pointsToken: (adSlotId: string) => ['me', 'points', 'token', adSlotId],
  adsterraStats: (startDate: string, finishDate: string) => ['adsterra', 'stats', startDate, finishDate],

  manga: (id: number) => ['manga', id],
  search: (searchParams: URLSearchParams, locale: string) => ['search', locale, Object.fromEntries(searchParams)],
  searchSuggestions: (query: string, locale: string) => ['search', 'suggestions', locale, query],
  posts: (filter: PostFilter, mangaId?: number, username?: string) => ['posts', filter, { mangaId, username }],
  realtimeAnalytics: ['realtime-analytics'],
  trendingKeywords: (locale: string) => ['trending-keywords', locale],
  tag: (category: string, page: number, locale: string) => ['tag', category, page, locale],
  webtoonEpisode: (provider: string, domain: string, path: string) => ['webtoon', 'episode', provider, domain, path],
  webtoonList: (provider: string, domain: string) => ['webtoon', 'list', provider, domain],
  webtoonSeries: (provider: string, domain: string, path: string) => ['webtoon', 'series', provider, domain, path],
}
