apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook-warning
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: alertmanager-discord-webhook-warning
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: url
      remoteRef:
        key: monitoring/alertmanager-discord-webhook-warning
        property: url
