export const env = {
  NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV ?? 'local',
  NEXT_PUBLIC_API_ORIGIN: process.env.NEXT_PUBLIC_API_ORIGIN ?? 'http://localhost:3002',
  NEXT_PUBLIC_APP_ORIGIN: process.env.NEXT_PUBLIC_APP_ORIGIN ?? 'http://localhost:3000',
  NEXT_PUBLIC_COMMIT_SHA: process.env.NEXT_PUBLIC_COMMIT_SHA ?? '',
  NEXT_PUBLIC_EDGE_PROXY_ORIGIN: process.env.NEXT_PUBLIC_EDGE_PROXY_ORIGIN ?? 'http://localhost:3001',
  NEXT_PUBLIC_IMAGE_PROXY_ORIGIN: process.env.NEXT_PUBLIC_IMAGE_PROXY_ORIGIN ?? 'http://localhost:3002',
  NEXT_PUBLIC_GTM_ID: process.env.NEXT_PUBLIC_GTM_ID ?? '',
  NEXT_PUBLIC_GTM_SCRIPT_URL: process.env.NEXT_PUBLIC_GTM_SCRIPT_URL ?? '',
  NEXT_PUBLIC_IOS_TESTFLIGHT_URL: process.env.NEXT_PUBLIC_IOS_TESTFLIGHT_URL ?? '',
  NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN ?? '',
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY ?? '1x00000000000000000000AA',
  NEXT_PUBLIC_VAPID_PUBLIC_KEY: process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY ?? '123',
} as const
