apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-prod

resources:
  - ../../base
  - cataloger-cronjob.yaml
  - hpa-api.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-api-secret.yaml
  - ingress.yaml
  - workload-identity-template/serviceaccount-api-google-auth.yaml
  - workload-identity-template/configmap-api-google-credentials.yaml

patches:
  - path: patch-api-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: workload-identity-template/patch-api-deployment-google-auth.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.in
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.01
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=prod,k8s.cluster.name=litomi-k3s

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:ee19a45f22267f806884760c78fd03b47b7f921ae0f0fe81a26142a77ff379d3
  - name: litomi-api
    newName: ghcr.io/litomi2026/litomi-api
    digest: sha256:461fdb725a5f027c5bd05cc69bd69a95fcc9d102d4fe507b3f113dad6b0762d3
  - name: litomi-cataloger
    newName: ghcr.io/litomi2026/litomi-cataloger
    digest: sha256:2fcb882daf8f1f8dcf05e3ed3bcbc58c8209bb66c20ddd79ff506571459f2bf2
