apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-prod

resources:
  - ../../base
  - hpa-backend.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-backend-secret.yaml
  - ingress.yaml
  - workload-identity-template/serviceaccount-backend-google-auth.yaml
  - workload-identity-template/configmap-backend-google-credentials.yaml

patches:
  - path: patch-backend-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: workload-identity-template/patch-backend-deployment-google-auth.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.in
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.01
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=prod,k8s.cluster.name=litomi-k3s

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:3aa27702eb6f04135de833f2d80ab3881ba98e2cfdce7ffd6899947ed4789129
  - name: litomi-backend
    newName: ghcr.io/litomi2026/litomi-backend
    digest: sha256:786ffc13ccb3225d6cac4e9d7950d15f937fbb0d656df2730e70df5b2a798968
