apiVersion: apps/v1
kind: Deployment
metadata:
  name: litomi-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: APP_POSTGRES_APPLICATION_NAME
              value: litomi-api
            - name: CATALOG_POSTGRES_APPLICATION_NAME
              value: litomi-api-catalog
