apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litomi-backend-file
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: litomi-backend-file
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: litomi-stg/litomi-backend-file
