apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-stg

resources:
  - ../../base
  - hpa-backend.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-backend-secret.yaml
  - ingress.yaml
  - workload-identity-template/serviceaccount-backend-google-auth.yaml
  - workload-identity-template/configmap-backend-google-credentials.yaml

patches:
  - path: patch-backend-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: workload-identity-template/patch-backend-deployment-google-auth.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ENV=stg
      - APP_ORIGIN=https://stg.litomi.in
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.3
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=stg,k8s.cluster.name=litomi-k3s
      - IMAGE_PROXY_UPSTREAM_PROXY_URL=http://litomi-image-egress-proxy:8080
      - IMAGE_PROXY_UPSTREAM_PROXY_HOST_SUFFIXES=k-hentai.org
images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:305fecaaee480e95fe0d318ad1ba6dac2e78132f02d9990f382bd0d333e36e81
  - name: litomi-backend
    newName: ghcr.io/litomi2026/litomi-backend
    digest: sha256:b1314b702c00d0d14666a6f9707613dea2c46279a521e087bba3a2cfd0c1fd08
  - name: litomi-spoofdpi
    newName: ghcr.io/litomi2026/litomi-spoofdpi
    digest: sha256:03da1c63fc171cfa138c144c030f3e15a509c7596af1fda7e0b2964c200d57a2
