apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-stg

resources:
  - ../../base
  - hpa-backend.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-backend-secret.yaml
  - ingress.yaml
  - workload-identity-template/serviceaccount-backend-google-auth.yaml
  - workload-identity-template/configmap-backend-google-credentials.yaml

patches:
  - path: patch-backend-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: workload-identity-template/patch-backend-deployment-google-auth.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ENV=stg
      - APP_ORIGIN=https://stg.litomi.in
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.3
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=stg,k8s.cluster.name=litomi-k3s
      - IMAGE_PROXY_UPSTREAM_PROXY_URL=http://litomi-image-egress-proxy:8080
      - IMAGE_PROXY_UPSTREAM_PROXY_HOST_SUFFIXES=k-hentai.org
images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:1da12920650760e8dccdfcaf53b4b616a20eaab3fa75269a51d8a860eb500863
  - name: litomi-backend
    newName: ghcr.io/litomi2026/litomi-backend
    digest: sha256:e03a9800190633757374f4a07dcc380a6d390c8a67b41fe4501a89a906593a7a
  - name: litomi-spoofdpi
    newName: ghcr.io/litomi2026/litomi-spoofdpi
    digest: sha256:9a8b868117e73e9f88d1348068b596743c3d451c8b439118d99095e7a30996b5
