apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-stg

resources:
  - ../../base
  - hpa-backend.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-backend-secret.yaml
  - ingress.yaml

patches:
  - path: patch-backend-deployment.yaml
  - path: patch-web-deployment.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ORIGIN=https://stg.litomi.in
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.3
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=stg,k8s.cluster.name=litomi-k3s
      - POSTGRES_HEALTHCHECK_CACHE_MS=15000

images:
  - name: litomi-web
    newName: ghcr.io/gwak2837/litomi-web
    digest: sha256:dca88fff0dbdb518094812fc28c617b5e461ead42cef869f3f694ad1d909e1fb
  - name: litomi-backend
    newName: ghcr.io/gwak2837/litomi-backend
    digest: sha256:5b038415b19090a389209968cf5215d827b234b91529e0bfe3484ab021d37a1b
