apiVersion: apps/v1
kind: Deployment
metadata:
  name: litomi-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: POSTGRES_APPLICATION_NAME
              value: litomi-backend-stg
            - name: POSTGRES_POOL_MAX
              value: '1'
