export type ProblemDetails = {
  /**
   * A URI reference that identifies the problem type.
   * We use: https://<origin>/problems/<code>
   */
  type: string
  /**
   * A short, human-readable summary of the problem type.
   * Should be stable and "minimally understandable".
   */
  title: string
  /**
   * The HTTP status code generated by the origin server for this occurrence.
   */
  status: number
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   * (UI message: friendly ~요 style)
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string
}

export const PROBLEM_CONTENT_TYPE = 'application/problem+json'

export function createProblemTypeUrl(origin: string, code: string): string {
  const safeOrigin = origin.replace(/\/+$/, '')
  const safeCode = encodeURIComponent(code)

  try {
    const url = new URL(safeOrigin)
    url.protocol = 'https:'
    return `${url.origin}/problems/${safeCode}`
  } catch {
    return `${safeOrigin}/problems/${safeCode}`
  }
}

export function getStatusTitle(status: number): string {
  if (status === 400) return '잘못된 요청이에요'
  if (status === 401) return '로그인이 필요해요'
  if (status === 403) return '권한이 없어요'
  if (status === 404) return '찾을 수 없어요'
  if (status === 409) return '요청이 충돌했어요'
  if (status === 408) return '요청 시간이 초과됐어요'
  if (status === 429) return '요청이 너무 많아요'
  if (status === 499) return '요청이 취소됐어요'
  if (status === 500) return '서버 오류가 발생했어요'
  if (status === 502) return '외부 서비스 오류예요'
  if (status === 503) return '서비스를 사용할 수 없어요'
  if (status === 504) return '게이트웨이 시간이 초과됐어요'
  return '오류가 발생했어요'
}

export function isProblemDetails(value: unknown): value is ProblemDetails {
  if (typeof value !== 'object' || value === null) {
    return false
  }

  const record = value as Record<string, unknown>
  return (
    typeof record.type === 'string' &&
    typeof record.title === 'string' &&
    typeof record.status === 'number' &&
    (record.detail === undefined || typeof record.detail === 'string') &&
    (record.instance === undefined || typeof record.instance === 'string')
  )
}
