apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: metrics-server
          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: 200m
              memory: 128Mi
