apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - projects/platform.yaml
  - projects/litomi.yaml

  - applications/platform-vault.yaml
  - applications/platform-external-secrets.yaml
  - applications/platform-metrics-server.yaml
  - applications/platform-cloudflared.yaml
  - applications/platform-monitoring.yaml
  - applications/platform-logging-loki.yaml
  - applications/platform-logging-fluent-bit.yaml
  - applications/platform-tracing-tempo.yaml
  - applications/platform-tracing-otel-collector.yaml
  - applications/platform-minio-operator.yaml
  - applications/platform-minio.yaml
  - applications/platform-velero.yaml
  - applications/platform-argocd.yaml

  - applications/litomi-stg.yaml
  - applications/litomi-prod.yaml
