apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-velero
  annotations:
    # ESO가 먼저 설치돼야(=CRD/컨트롤러) ExternalSecret/SecretStore를 적용할 수 있어요.
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: platform
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.3.2
      helm:
        releaseName: velero
        valueFiles:
          - $values/k8s/platform/velero/velero.values.yaml
    - repoURL: https://github.com/gwak2837/litomi.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/gwak2837/litomi.git
      targetRevision: main
      path: k8s/platform/velero
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
