apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-minio
  annotations:
    # ESO가 먼저 설치돼야 ExternalSecret/SecretStore를 적용할 수 있어요.
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: platform
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: minio
      targetRevision: 17.0.21
      helm:
        releaseName: minio
        valueFiles:
          - $values/k8s/platform/minio/minio.values.yaml
    - repoURL: https://github.com/gwak2837/litomi.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/gwak2837/litomi.git
      targetRevision: main
      path: k8s/platform/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
